# Generated by Django 4.2.16 on 2024-11-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='created_when',
            new_name='created_at',
        ),
    ]
