# Generated by Django 4.2.16 on 2024-11-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_created_when_passwordreset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
